### ISSUE TITLE
Remaining venues

### ISSUE THREAD

**Issue by drewbrew** [hsv-dot-beer/hsvdotbeer#102]
## Venues we should theoretically be able to support
- The Bar at 805 (DigitalPour, but no site that I know of)
- Pints and Pixels (Untappd, but doesn't expose the tap list on their site) (2019-03-28: @mjcarroll emailed them about it)
- Below the Radar (Untappd, but doesn't have a functioning site to expose the tap list on)

## Venues we'll never support
- Green Bus
- Salty Nut
- OBB
- Church Street Wine Shoppe

### Untappd
- Cajun Steamer (Twickenham, no beer menu on site)
- Anaheim Chili (they have a beer menu on their site, but ~it's down~ they let their domain get hijacked and their email address bounced)
- End Zone (no beer menu on their site)
- Stand Up Live (no beer menu on their site)
- West End Outdoors (Athens, no website)

**Comment by mjcarroll** [comment]
Would it make sense to split this into issues per venue and add tags?  We now have two tracking issues like this.

**Comment by drewbrew** [comment]
These were mostly set up as places to drop ideas. I'm good with splitting them.

**Comment by drewbrew** [comment]
Closing this since we don't have anything to do until new venues pop up.
