### ISSUE TITLE
Setup fuzzy search

### ISSUE THREAD

**Issue by drewmcdowell** [hsv-dot-beer/hsvdotbeer#131]
The search field will search across multiple datasets: beer name, manufacturer name, and beer style.  The logic for this will need to be created.

**Comment by drewbrew** [comment]
The backend logic is already in place (https://github.com/hsv-dot-beer/hsvdotbeer/pull/114/files#diff-34662951a73701f9d9d832ad6e4a5669R31), so this needs to be moved to the frontend project when @mjcarroll posts that.

URL: /api/v1/beers/?search=my+favorite+beer

That'll search all these fields for containing that value (case-insensitive):
- name
- alternate names
- style name
- style category name
- manufacturer name
- manufacturer alternate names

**Comment by drewbrew** [comment]
This works on the version demonstrated last night. Closing.
