### ISSUE TITLE
Add Hops n Guac to venues list

### ISSUE THREAD

**Issue by Chandler-Davidson** [hsv-dot-beer/hsvdotbeer#235]
[Hops n Guac](https://www.hopsnguac.com/) opened recently and is a great candidate to be added. They use [iPourIt](https://www.ipouritinc.com/) and act as a self-serve bar, I'm unsure if they have an API that can be exposed.

**Comment by drewbrew** [comment]
Hmm, never heard of iPourIt. I'll take a look.

**Comment by drewbrew** [comment]
Given that they [outsourced their mobile app development](https://www.saritasa.com/portfolio/ipourit-android-app-development/), I'm willing to guess that if they do have one, it's not a very good one and definitely isn't public.

**Comment by mjcarroll** [comment]
I did a quick look and didn't see anything on github/google that would indicate an API, but would maybe be worth asking.  @Chandler-Davidson want to reach out and see if it is doable?

**Comment by Chandler-Davidson** [comment]
Sure! I'll reach out and see if its published anywhere.

**Comment by drewbrew** [comment]
Did they ever get back to you, @Chandler-Davidson?

**Comment by Chandler-Davidson** [comment]
No response from an email or social media. I'll go ahead and close the ticket until they become more responsive.

**Comment by drewbrew** [comment]
I wish I were surprised. So it goes.

Thanks for checking!
