### ISSUE TITLE
Idea: tweet new beer announcements

### ISSUE THREAD

**Issue by drewbrew** [hsv-dot-beer/hsvdotbeer#270]
Idea: if a beer is new to us, tweet it out, maybe something of the form:

```
New to us #beer: Cool Beer by Some Brewery, a 5% American Pale Ale. Find it on tap @venue: https://hsv.beer/venue/this-venue/
```

**Comment by mjcarroll** [comment]
Great idea!  Probably gluing what we've got against some Twitter APIs.

**Comment by drewbrew** [comment]
Yep, it would basically be a signal on beer create to queue a post 10 minutes later (to give us a chance at an untappd lookup)

**Comment by drewbrew** [comment]
Also I can piggyback on that to send a Twitter DM to myself with tracebacks when parsing fails.
