### ISSUE TITLE
Create a moderation queue for new beers

### ISSUE THREAD

**Issue by drewbrew** [hsv-dot-beer/hsvdotbeer#30]
If we get a beer coming in that we can't cleanly parse (likely because its style doesn't map to BJCP), use a moderation queue to make our lives way easier.

Also consider adding a `StyleMapping` model:

- `BeerStyle` (FK)
- `provider` (CharField, same choices as `Venue.taplist_provider`)
- `provider_style_name`

That way we can auto-resolve future styles with the same name.

**Comment by drewbrew** [comment]
I had some shower thoughts on how to do this since django-moderation is abandonware.

0. Add a `block_automatic_updates` field to both mfg and beer
1. Create an alternate names table for manufacturer and beer:
  - FK to parent table
  - name (unique)
2. Change the beer/mfg lookup to look for either the name or alternate name matching
3. Add a detail route to both the beer and mfg routes: `POST /<model>/<pk>/mergefrom/` with body `{"id": <other_pk>}`
4. That route would:
   - set the block auto updates field
   - move all related objects from <other_pk> to <pk>
   - delete <other_pk>
5. Update the parsers to avoid updating models with auto updates blocked

It would obviously need a frontend (hello, datatables), but how does that sound from an API standpoint?

**Comment by drewbrew** [comment]
@mjcarroll ☝️

**Comment by mjcarroll** [comment]
Yup, that sounds :100: reasonable, I was just thinking about this and had a similar idea (although with much sketchier impl details).
