### ISSUE TITLE
Drop asterisks in Nook beers

### ISSUE THREAD

**Issue by drewbrew** [hsv-dot-beer/hsvdotbeer#45]
The Nook uses an asterisk on some beers to denote... something (super expensive beers?).

We need to strip those out.

**Comment by mjcarroll** [comment]
I think it's serving temperature:
> Our beer lists include a Beer Advocate derived international rating and style.  *Served at recommended 50-55º F

**Comment by drewbrew** [comment]
Ah, that makes sense.
